name: Hey!

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating your first issue, a developer will look into it.  Keep hunting for more bugs! :)'
        pr-message: 'Thanks for creating your first pull request, a developer will look into it.  Keep coding on! :)'
